"use client"

import * as React from "react"
import { Utensils, Sparkles, ChefHat, Calendar, ShoppingBasket, Plus, Search, Loader2, Camera, X, Check } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogFooter, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger 
} from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { naturalLanguageMealSuggestion } from "@/ai/flows/natural-language-meal-suggestion"
import { generateShoppingList } from "@/ai/flows/ai-meal-plan-shopping-list-generation"
import { identifyRecipe } from "@/ai/flows/identify-recipe-flow"
import { useToast } from "@/hooks/use-toast"
import { useUser, useCollection, useFirestore } from "@/firebase"
import { collection, query, where, addDoc, serverTimestamp, doc, setDoc } from "firebase/firestore"
import { useRouter } from "next/navigation"

export default function MealPlannerPage() {
  const { profile } = useUser()
  const db = useFirestore()
  const router = useRouter()
  const { toast } = useToast()
  
  const [queryStr, setQueryStr] = React.useState("")
  const [isAiLoading, setIsAiLoading] = React.useState(false)
  const [isGeneratingList, setIsGeneratingList] = React.useState(false)
  const [aiSuggestions, setAiSuggestions] = React.useState<any[]>([])
  
  // Add Recipe Dialog State
  const [isAddOpen, setIsAddOpen] = React.useState(false)
  const [newRecipeTitle, setNewRecipeTitle] = React.useState("")

  // Camera State
  const [isCameraOpen, setIsCameraOpen] = React.useState(false)
  const [hasCameraPermission, setHasCameraPermission] = React.useState(false)
  const [isScanning, setIsScanning] = React.useState(false)
  const videoRef = React.useRef<HTMLVideoElement>(null)
  const canvasRef = React.useRef<HTMLCanvasElement>(null)

  // Fetch Family Recipes
  const recipesQuery = React.useMemo(() => {
    if (!db || !profile?.familyId) return null
    return query(collection(db, "recipes"), where("familyId", "==", profile.familyId))
  }, [db, profile?.familyId])
  const { data: recipes, loading: recipesLoading } = useCollection(recipesQuery)

  // Fetch Current Meal Plan
  const mealPlanQuery = React.useMemo(() => {
    if (!db || !profile?.familyId) return null
    return query(collection(db, "mealPlans"), where("familyId", "==", profile.familyId))
  }, [db, profile?.familyId])
  const { data: mealPlans } = useCollection(mealPlanQuery)
  const currentPlan = mealPlans?.[0]

  const handleSuggest = async () => {
    if (!queryStr) return
    setIsAiLoading(true)
    try {
      const result = await naturalLanguageMealSuggestion({ query: queryStr })
      setAiSuggestions(result.suggestions)
      toast({
        title: "Suggestions ready!",
        description: result.summary,
      })
    } catch (e) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to get suggestions. Please try again.",
      })
    } finally {
      setIsAiLoading(false)
    }
  }

  const handleAddRecipe = async () => {
    if (!db || !profile?.familyId || !newRecipeTitle) return
    
    const recipeData = {
      familyId: profile.familyId,
      title: newRecipeTitle,
      ingredients: [],
      instructions: "",
      tags: ["New"],
      createdAt: serverTimestamp(),
    }

    try {
      await addDoc(collection(db, "recipes"), recipeData)
      setIsAddOpen(false)
      setNewRecipeTitle("")
      toast({ title: "Recipe Added", description: "Start adding ingredients to your new recipe!" })
    } catch (e) {
      toast({ variant: "destructive", title: "Error", description: "Could not save recipe." })
    }
  }

  const handleGenerateShoppingList = async () => {
    if (!currentPlan || !recipes || recipes.length === 0) {
      toast({ title: "No Plan Found", description: "Add some meals to your weekly plan first." })
      return
    }

    setIsGeneratingList(true)
    try {
      const result = await generateShoppingList({
        mealPlan: {
          weekStart: currentPlan.weekStart || new Date().toISOString().split('T')[0],
          days: currentPlan.days || {}
        },
        recipes: recipes.map(r => ({
          id: r.id,
          title: r.title,
          ingredients: r.ingredients || []
        }))
      })

      const newListRef = doc(collection(db, "shoppingLists"))
      await setDoc(newListRef, {
        familyId: profile?.familyId,
        name: result.listName,
        items: result.items.map(item => ({ ...item, checked: false })),
        isAutoGenerated: true,
        createdAt: serverTimestamp()
      })

      toast({
        title: "Shopping List Generated!",
        description: `Created "${result.listName}" with ${result.items.length} items.`,
      })
      router.push("/shopping")
    } catch (e) {
      console.error(e)
      toast({ variant: "destructive", title: "AI Error", description: "Failed to generate shopping list." })
    } finally {
      setIsGeneratingList(false)
    }
  }

  // Camera Logic
  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } })
      setHasCameraPermission(true)
      if (videoRef.current) {
        videoRef.current.srcObject = stream
      }
    } catch (error) {
      console.error('Error accessing camera:', error)
      setHasCameraPermission(false)
      toast({
        variant: 'destructive',
        title: 'Camera Access Denied',
        description: 'Please enable camera permissions in your browser settings to use the scanner.',
      })
    }
  }

  const stopCamera = () => {
    if (videoRef.current && videoRef.current.srcObject) {
      const tracks = (videoRef.current.srcObject as MediaStream).getTracks()
      tracks.forEach(track => track.stop())
    }
    setIsCameraOpen(false)
  }

  const captureAndScan = async () => {
    if (!videoRef.current || !canvasRef.current || !db || !profile?.familyId) return

    setIsScanning(true)
    const context = canvasRef.current.getContext('2d')
    canvasRef.current.width = videoRef.current.videoWidth
    canvasRef.current.height = videoRef.current.videoHeight
    context?.drawImage(videoRef.current, 0, 0)
    
    const photoDataUri = canvasRef.current.toDataURL('image/jpeg')

    try {
      const result = await identifyRecipe({ photoDataUri })
      
      // Save identified recipe to Firestore
      const recipeData = {
        familyId: profile.familyId,
        ...result,
        createdAt: serverTimestamp(),
      }
      
      await addDoc(collection(db, "recipes"), recipeData)
      
      toast({
        title: "Recipe Identified!",
        description: `"${result.title}" has been added to your recipe box.`,
      })
      stopCamera()
    } catch (e) {
      console.error(e)
      toast({
        variant: "destructive",
        title: "Scan Failed",
        description: "Could not identify the recipe. Please try again with better lighting.",
      })
    } finally {
      setIsScanning(false)
    }
  }

  const daysOfWeek = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

  return (
    <div className="flex flex-col p-4 md:p-8 space-y-8 max-w-7xl mx-auto pb-24">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-headline font-bold tracking-tight text-primary">Meal Planner & Recipe Box</h1>
          <p className="text-muted-foreground font-medium">Smart planning for the Kapendeka universe</p>
        </div>
        <div className="flex items-center gap-2">
          <Button 
            variant="outline" 
            className="rounded-xl h-11 px-6 font-bold border-primary/20 text-primary"
            onClick={() => router.push("/shopping")}
          >
            <ShoppingBasket className="h-4 w-4 mr-2" /> Shopping Lists
          </Button>
          
          <Dialog open={isCameraOpen} onOpenChange={(open) => { if (open) startCamera(); else stopCamera(); setIsCameraOpen(open); }}>
            <DialogTrigger asChild>
              <Button className="rounded-xl h-11 px-6 font-bold bg-accent shadow-lg shadow-accent/20">
                <Camera className="h-4 w-4 mr-2" /> Scan Recipe
              </Button>
            </DialogTrigger>
            <DialogContent className="rounded-2xl sm:max-w-2xl overflow-hidden">
              <DialogHeader>
                <DialogTitle>AI Recipe Scanner</DialogTitle>
                <DialogDescription>Point your camera at a cookbook or a meal to identify it.</DialogDescription>
              </DialogHeader>
              
              <div className="relative aspect-video rounded-xl bg-black overflow-hidden mt-4">
                <video ref={videoRef} className="w-full h-full object-cover" autoPlay muted playsInline />
                <canvas ref={canvasRef} className="hidden" />
                
                {!hasCameraPermission && !isScanning && (
                  <div className="absolute inset-0 flex items-center justify-center p-6 text-center">
                    <Alert variant="destructive" className="bg-black/80 border-rose-500 text-white">
                      <AlertTitle>Camera Required</AlertTitle>
                      <AlertDescription>Please grant camera access to use the scanning feature.</AlertDescription>
                    </Alert>
                  </div>
                )}

                {isScanning && (
                  <div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center text-white space-y-4">
                    <Loader2 className="h-12 w-12 animate-spin text-accent" />
                    <p className="font-bold text-lg animate-pulse uppercase tracking-widest">Universe AI Analyzing...</p>
                  </div>
                )}
              </div>

              <DialogFooter className="mt-6 flex gap-2">
                <Button variant="outline" onClick={stopCamera} disabled={isScanning}>Cancel</Button>
                <Button 
                  onClick={captureAndScan} 
                  disabled={isScanning || !hasCameraPermission}
                  className="bg-accent hover:bg-accent/90"
                >
                  {isScanning ? "Processing..." : "Capture & Identify"}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>

          <Dialog open={isAddOpen} onOpenChange={setIsAddOpen}>
            <DialogTrigger asChild>
              <Button className="rounded-xl h-11 px-6 font-bold bg-primary shadow-lg shadow-primary/20">
                <Plus className="h-4 w-4 mr-2" /> Add Recipe
              </Button>
            </DialogTrigger>
            <DialogContent className="rounded-2xl">
              <DialogHeader>
                <DialogTitle>New Recipe</DialogTitle>
                <DialogDescription>Add a favorite dish to the family collection.</DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="grid gap-2">
                  <Label htmlFor="recipe-title">Title</Label>
                  <Input 
                    id="recipe-title" 
                    placeholder="e.g. Mama's Chakalaka" 
                    value={newRecipeTitle}
                    onChange={(e) => setNewRecipeTitle(e.target.value)}
                  />
                </div>
              </div>
              <DialogFooter>
                <Button onClick={handleAddRecipe} disabled={!newRecipeTitle}>Create Recipe</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </header>

      {/* AI Search Section */}
      <Card className="rounded-3xl border-none shadow-xl bg-gradient-to-br from-primary to-indigo-700 text-white p-1">
        <CardContent className="p-8 space-y-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Sparkles className="h-6 w-6 text-accent animate-pulse" />
              <h2 className="text-2xl font-bold">What's for dinner?</h2>
            </div>
            <p className="text-primary-foreground/80 font-medium">Ask AI to suggest a meal based on your preferences or scan a photo to add a recipe.</p>
          </div>
          <div className="flex flex-col md:flex-row gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input 
                placeholder="Suggest a healthy dinner with chicken..." 
                className="h-14 pl-12 rounded-2xl border-none bg-white/90 text-primary-foreground font-medium text-lg placeholder:text-muted-foreground focus-visible:ring-accent"
                value={queryStr}
                onChange={(e) => setQueryStr(e.target.value)}
              />
            </div>
            <Button 
              onClick={handleSuggest}
              disabled={isAiLoading || !queryStr}
              className="h-14 px-8 rounded-2xl bg-accent text-white font-bold hover:bg-accent/90 shadow-lg shadow-accent/20"
            >
              {isAiLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : "Get AI Suggestions"}
            </Button>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <h3 className="text-xl font-bold flex items-center gap-2">
            <ChefHat className="h-5 w-5 text-primary" />
            {aiSuggestions.length > 0 ? "AI Recommended Recipes" : "Family Recipe Box"}
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {recipesLoading ? (
              [1, 2, 3, 4].map(i => <div key={i} className="h-64 bg-muted animate-pulse rounded-2xl" />)
            ) : (aiSuggestions.length > 0 ? aiSuggestions : recipes || []).length > 0 ? (
              (aiSuggestions.length > 0 ? aiSuggestions : recipes || []).map((recipe, i) => (
                <Card key={recipe.id || i} className="group overflow-hidden rounded-2xl hover:shadow-xl transition-all border-none shadow-md cursor-pointer">
                  <div className="h-48 bg-muted relative overflow-hidden">
                    <img 
                      src={`https://picsum.photos/seed/${recipe.id || i + 50}/600/400`} 
                      alt={recipe.title} 
                      className="object-cover w-full h-full group-hover:scale-110 transition-transform duration-500" 
                    />
                    <div className="absolute top-3 right-3">
                      <Button size="icon" variant="secondary" className="h-8 w-8 rounded-full bg-white/80 backdrop-blur-sm">
                        <Plus className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                  <CardContent className="p-5">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-bold text-lg group-hover:text-primary transition-colors">{recipe.title}</h4>
                      <span className="text-xs text-muted-foreground font-bold">{recipe.prepTime || "25 min"}</span>
                    </div>
                    <div className="flex gap-2 flex-wrap">
                      {(recipe.tags || []).map((tag: string) => (
                        <Badge key={tag} variant="outline" className="text-[10px] font-bold uppercase py-0 px-2 border-primary/20 text-primary">
                          {tag}
                        </Badge>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ))
            ) : (
              <div className="col-span-full py-12 text-center bg-muted/20 rounded-2xl border-2 border-dashed">
                <p className="text-muted-foreground font-medium">Your recipe box is empty. Scan a photo or add your first favorite!</p>
              </div>
            )}
          </div>
        </div>

        <div className="space-y-6">
          <h3 className="text-xl font-bold flex items-center gap-2">
            <Calendar className="h-5 w-5 text-primary" />
            Weekly Meal Plan
          </h3>
          <Card className="rounded-2xl border-none shadow-sm overflow-hidden">
            <div className="bg-muted/30 p-4 font-bold text-sm text-center border-b uppercase tracking-tighter">
              {currentPlan?.weekStart ? `Week of ${currentPlan.weekStart}` : 'Plan Your Week'}
            </div>
            <CardContent className="p-4 space-y-4">
              {daysOfWeek.map((day) => {
                const meal = currentPlan?.days?.[day]?.dinner
                const recipe = recipes?.find(r => r.id === meal)
                return (
                  <div key={day} className="flex items-center gap-4 group cursor-pointer hover:bg-muted/20 p-2 rounded-xl transition-colors">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center font-bold text-primary text-xs">
                      {day.substring(0, 3)}
                    </div>
                    <div className="flex-1">
                      <div className="text-sm font-bold truncate">
                        {recipe?.title || 'Dinner not set'}
                      </div>
                      <div className="text-[10px] text-muted-foreground font-medium">Dinner</div>
                    </div>
                    <Plus className="h-4 w-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                )
              })}
              <Button 
                variant="outline" 
                className="w-full mt-4 font-bold rounded-xl h-11 border-primary/20 text-primary"
                onClick={handleGenerateShoppingList}
                disabled={isGeneratingList}
              >
                {isGeneratingList ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Analyzing Recipes...
                  </>
                ) : (
                  "Generate AI Shopping List"
                )}
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
