"use client"

import * as React from "react"
import { 
  ShoppingBasket, 
  Plus, 
  Trash2, 
  CheckCircle2, 
  Circle, 
  Filter, 
  MoreVertical,
  ArrowLeft,
  Loader2,
  Sparkles
} from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Checkbox } from "@/components/ui/checkbox"
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuTrigger 
} from "@/components/ui/dropdown-menu"
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogFooter, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger 
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useUser, useCollection, useFirestore } from "@/firebase"
import { 
  collection, 
  query, 
  where, 
  addDoc, 
  serverTimestamp, 
  orderBy, 
  updateDoc, 
  doc, 
  deleteDoc 
} from "firebase/firestore"
import { useToast } from "@/hooks/use-toast"
import { errorEmitter } from "@/firebase/error-emitter"
import { FirestorePermissionError } from "@/firebase/errors"
import { useRouter } from "next/navigation"

export default function ShoppingPage() {
  const { profile } = useUser()
  const db = useFirestore()
  const router = useRouter()
  const { toast } = useToast()
  
  const [isAddOpen, setIsAddOpen] = React.useState(false)
  const [newListName, setNewListName] = React.useState("")
  const [activeListId, setActiveListId] = React.useState<string | null>(null)

  // Fetch all shopping lists for the family
  const listsQuery = React.useMemo(() => {
    if (!db || !profile?.familyId) return null
    return query(
      collection(db, "shoppingLists"),
      where("familyId", "==", profile.familyId),
      orderBy("createdAt", "desc")
    )
  }, [db, profile?.familyId])
  
  const { data: lists, loading } = useCollection(listsQuery)

  const activeList = React.useMemo(() => {
    if (!lists) return null
    if (activeListId) return lists.find(l => l.id === activeListId)
    return lists[0]
  }, [lists, activeListId])

  const handleCreateList = () => {
    if (!db || !profile?.familyId || !newListName) return

    const data = {
      familyId: profile.familyId,
      name: newListName,
      items: [],
      isAutoGenerated: false,
      createdAt: serverTimestamp()
    }

    addDoc(collection(db, "shoppingLists"), data)
      .then(() => {
        setIsAddOpen(false)
        setNewListName("")
        toast({ title: "List Created", description: `"${newListName}" is ready for items.` })
      })
      .catch((err) => {
        errorEmitter.emit("permission-error", new FirestorePermissionError({
          path: "shoppingLists",
          operation: "create",
          requestResourceData: data
        }))
      })
  }

  const toggleItem = (listId: string, itemIndex: number) => {
    if (!db || !activeList) return
    
    const updatedItems = [...activeList.items]
    updatedItems[itemIndex] = { 
      ...updatedItems[itemIndex], 
      checked: !updatedItems[itemIndex].checked 
    }

    const listRef = doc(db, "shoppingLists", listId)
    updateDoc(listRef, { items: updatedItems })
      .catch((err) => {
        errorEmitter.emit("permission-error", new FirestorePermissionError({
          path: `shoppingLists/${listId}`,
          operation: "update"
        }))
      })
  }

  const deleteList = (listId: string) => {
    if (!db) return
    deleteDoc(doc(db, "shoppingLists", listId))
      .then(() => {
        if (activeListId === listId) setActiveListId(null)
        toast({ title: "List Deleted" })
      })
  }

  return (
    <div className="flex flex-col p-4 md:p-8 space-y-8 max-w-7xl mx-auto">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="rounded-xl" onClick={() => router.push("/")}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-3xl font-headline font-bold tracking-tight text-primary">Shopping Lists</h1>
            <p className="text-muted-foreground font-medium">Collaborative groceries for the Kapendeka universe</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Dialog open={isAddOpen} onOpenChange={setIsAddOpen}>
            <DialogTrigger asChild>
              <Button className="rounded-xl h-11 px-6 font-bold bg-primary shadow-lg shadow-primary/20">
                <Plus className="h-4 w-4 mr-2" /> New List
              </Button>
            </DialogTrigger>
            <DialogContent className="rounded-2xl">
              <DialogHeader>
                <DialogTitle>Create Shopping List</DialogTitle>
                <DialogDescription>Add a new list for groceries, hardware, or special events.</DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="grid gap-2">
                  <Label htmlFor="list-name">Name</Label>
                  <Input 
                    id="list-name" 
                    placeholder="e.g. Woolworths Weekly" 
                    value={newListName}
                    onChange={(e) => setNewListName(e.target.value)}
                  />
                </div>
              </div>
              <DialogFooter>
                <Button onClick={handleCreateList} disabled={!newListName}>Create</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Sidebar: All Lists */}
        <div className="lg:col-span-4 space-y-4">
          <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider px-2 flex items-center justify-between">
            Your Lists
            <Badge variant="outline" className="text-[10px]">{lists?.length || 0}</Badge>
          </h3>
          <div className="space-y-2">
            {loading ? (
              [1, 2, 3].map(i => <div key={i} className="h-16 bg-muted animate-pulse rounded-2xl" />)
            ) : (lists || []).length > 0 ? (
              lists?.map((list) => (
                <button
                  key={list.id}
                  onClick={() => setActiveListId(list.id)}
                  className={`w-full flex items-center justify-between p-4 rounded-2xl transition-all border text-left ${
                    (activeListId === list.id || (!activeListId && list === lists[0]))
                      ? "bg-primary text-primary-foreground border-primary shadow-lg shadow-primary/10"
                      : "bg-white border-transparent hover:border-primary/20"
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <div className={`p-2 rounded-xl ${activeListId === list.id ? "bg-white/20" : "bg-primary/5 text-primary"}`}>
                      {list.isAutoGenerated ? <Sparkles className="h-4 w-4" /> : <ShoppingBasket className="h-4 w-4" />}
                    </div>
                    <div>
                      <div className="font-bold text-sm truncate max-w-[150px]">{list.name}</div>
                      <div className={`text-[10px] font-medium opacity-70`}>
                        {list.items?.length || 0} items
                      </div>
                    </div>
                  </div>
                  {list.isAutoGenerated && <Badge className="bg-accent/20 text-accent text-[8px] font-bold uppercase border-none px-1.5 h-4">AI</Badge>}
                </button>
              ))
            ) : (
              <div className="text-center py-8 px-4 bg-muted/20 rounded-2xl border-2 border-dashed">
                <p className="text-xs text-muted-foreground font-medium">No shopping lists found. Create your first list!</p>
              </div>
            )}
          </div>
        </div>

        {/* Main Content: Active List Items */}
        <div className="lg:col-span-8 space-y-6">
          {activeList ? (
            <Card className="rounded-[2rem] border-none shadow-xl bg-white overflow-hidden min-h-[500px]">
              <CardHeader className="bg-muted/30 pb-6 border-b">
                <div className="flex items-center justify-between">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <CardTitle className="text-2xl font-bold">{activeList.name}</CardTitle>
                      {activeList.isAutoGenerated && (
                        <Badge className="bg-accent text-white font-bold border-none text-[10px]">AI GENERATED</Badge>
                      )}
                    </div>
                    <CardDescription className="font-medium">
                      {activeList.items?.filter((i: any) => !i.checked).length} items remaining
                    </CardDescription>
                  </div>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" className="rounded-full">
                        <MoreVertical className="h-5 w-5" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="rounded-xl">
                      <DropdownMenuItem className="text-destructive font-bold" onClick={() => deleteList(activeList.id)}>
                        <Trash2 className="h-4 w-4 mr-2" /> Delete List
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </CardHeader>
              <CardContent className="p-6">
                <div className="space-y-1">
                  {activeList.items && activeList.items.length > 0 ? (
                    activeList.items.map((item: any, index: number) => (
                      <div 
                        key={index}
                        onClick={() => toggleItem(activeList.id, index)}
                        className={`flex items-center gap-4 p-4 rounded-xl cursor-pointer transition-all hover:bg-muted/30 ${
                          item.checked ? "opacity-50" : ""
                        }`}
                      >
                        <div className={`h-6 w-6 rounded-full border-2 flex items-center justify-center transition-colors ${
                          item.checked ? "bg-emerald-500 border-emerald-500 text-white" : "border-muted-foreground/30"
                        }`}>
                          {item.checked && <CheckCircle2 className="h-4 w-4" />}
                        </div>
                        <div className="flex-1">
                          <div className={`font-bold ${item.checked ? "line-through" : ""}`}>
                            {item.name}
                          </div>
                          {item.category && (
                            <div className="text-[10px] font-bold text-primary uppercase tracking-tighter">
                              {item.category}
                            </div>
                          )}
                        </div>
                        <div className="text-sm font-bold text-muted-foreground bg-muted/50 px-3 py-1 rounded-lg">
                          {item.quantity} {item.unit}
                        </div>
                      </div>
                    ))
                  ) : (
                    <div className="flex flex-col items-center justify-center py-20 text-center space-y-4">
                      <div className="h-16 w-16 bg-muted/30 rounded-full flex items-center justify-center">
                        <ShoppingBasket className="h-8 w-8 text-muted-foreground/30" />
                      </div>
                      <div>
                        <h4 className="font-bold">List is empty</h4>
                        <p className="text-sm text-muted-foreground max-w-[200px] mx-auto">
                          Add items to your list or generate them from the meal planner.
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="h-full flex items-center justify-center text-center p-12 bg-muted/20 rounded-[2rem] border-2 border-dashed">
              <div className="space-y-2">
                <ShoppingBasket className="h-12 w-12 text-muted-foreground/20 mx-auto" />
                <h3 className="font-bold text-lg">Select a list to start shopping</h3>
                <p className="text-sm text-muted-foreground">All your family's grocery lists will appear here.</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
