
"use client"

import * as React from "react"
import { 
  ShoppingBasket, 
  Plus, 
  Trash2, 
  CheckCircle2, 
  ArrowLeft,
  MoreVertical,
  Sparkles,
  ChevronLeft,
  ListIcon
} from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuTrigger 
} from "@/components/ui/dropdown-menu"
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogFooter, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger 
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useUser, useCollection, useSupabase } from "@/supabase"
import { useToast } from "@/hooks/use-toast"
import { useRouter } from "next/navigation"

export default function ShoppingPage() {
  const { profile } = useUser()
  const supabase = useSupabase()
  const router = useRouter()
  const { toast } = useToast()
  
  const [isAddOpen, setIsAddOpen] = React.useState(false)
  const [newListName, setNewListName] = React.useState("")
  const [activeListId, setActiveListId] = React.useState<string | null>(null)
  const [showListSelector, setShowListSelector] = React.useState(true)

  const listsQuery = React.useMemo(() => {
    if (!supabase || !profile?.familyId) return null
    return supabase.from("shoppingLists").select("*").eq("familyId", profile.familyId).order("createdAt", { ascending: false })
    
  }, [supabase, profile?.familyId])
  
  const { data: lists, loading } = useCollection(listsQuery)

  const activeList = React.useMemo(() => {
    if (!lists) return null
    if (activeListId) return lists.find(l => l.id === activeListId)
    return lists[0]
  }, [lists, activeListId])

  const handleSelect = (id: string) => {
    setActiveListId(id)
    if (window.innerWidth < 1024) {
      setShowListSelector(false)
    }
  }

  const handleCreateList = () => {
    if (!supabase || !profile?.familyId || !newListName) return
    const data = {
      familyId: profile.familyId,
      name: newListName,
      items: [],
      isAutoGenerated: false,
      createdAt: new Date().toISOString()
    }
    supabase.from("shoppingLists").insert([data]).select().single()
      .then(({ data: created }) => {
        setIsAddOpen(false)
        setNewListName("")
        if (created?.id) handleSelect(created.id)
        toast({ title: "List Created" })
      })
  }

  const toggleItem = (listId: string, itemIndex: number) => {
    if (!supabase || !activeList) return
    const updatedItems = [...activeList.items]
    updatedItems[itemIndex] = { ...updatedItems[itemIndex], checked: !updatedItems[itemIndex].checked }
    supabase.from("shoppingLists").update({ items: updatedItems }).eq("id", listId)
  }

  const deleteList = (listId: string) => {
    if (!supabase) return
    supabase.from("shoppingLists").delete().eq("id", listId)
      .then(() => {
        setActiveListId(null)
        setShowListSelector(true)
        toast({ title: "List Deleted" })
      })
  }

  return (
    <div className="flex flex-col p-4 md:p-8 space-y-6 max-w-7xl mx-auto h-full">
      <header className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          {!showListSelector && (
            <Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setShowListSelector(true)}>
              <ChevronLeft className="h-5 w-5" />
            </Button>
          )}
          <h1 className="text-2xl md:text-3xl font-headline font-bold text-primary">Shopping</h1>
        </div>
        <Dialog open={isAddOpen} onOpenChange={setIsAddOpen}>
          <DialogTrigger asChild>
            <Button className="rounded-xl h-10 px-4 font-bold bg-primary shadow-lg shadow-primary/20">
              <Plus className="h-4 w-4 mr-2" /> New
            </Button>
          </DialogTrigger>
          <DialogContent className="rounded-2xl">
            <DialogHeader><DialogTitle>New Shopping List</DialogTitle></DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <Label>List Name</Label>
                <Input placeholder="e.g. Weekly Groceries" value={newListName} onChange={(e) => setNewListName(e.target.value)} />
              </div>
            </div>
            <DialogFooter>
              <Button onClick={handleCreateList} disabled={!newListName} className="w-full">Create</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 h-full">
        {/* Mobile List Selector / Desktop Sidebar */}
        <div className={`${showListSelector ? "block" : "hidden lg:block"} lg:col-span-4 space-y-4`}>
          <div className="space-y-2">
            {loading ? (
              [1, 2, 3].map(i => <div key={i} className="h-16 bg-muted animate-pulse rounded-2xl" />)
            ) : lists?.map((list) => (
              <button
                key={list.id}
                onClick={() => handleSelect(list.id)}
                className={`w-full flex items-center justify-between p-4 rounded-2xl transition-all border text-left ${
                  (activeListId === list.id || (!activeListId && list === lists[0]))
                    ? "bg-primary text-primary-foreground border-primary shadow-lg"
                    : "bg-white border-transparent hover:bg-muted/50"
                }`}
              >
                <div className="flex items-center gap-3">
                  <div className={`p-2 rounded-xl ${activeListId === list.id ? "bg-white/20" : "bg-primary/5 text-primary"}`}>
                    {list.isAutoGenerated ? <Sparkles className="h-4 w-4" /> : <ShoppingBasket className="h-4 w-4" />}
                  </div>
                  <div>
                    <div className="font-bold text-sm truncate max-w-[150px]">{list.name}</div>
                    <div className="text-[10px] font-medium opacity-70">{list.items?.length || 0} items</div>
                  </div>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* List Content */}
        <div className={`${!showListSelector ? "block" : "hidden lg:block"} lg:col-span-8 space-y-6 h-full`}>
          {activeList ? (
            <Card className="rounded-[2rem] border-none shadow-xl bg-white overflow-hidden flex flex-col min-h-[400px]">
              <CardHeader className="bg-muted/30 pb-4 border-b">
                <div className="flex items-center justify-between">
                  <div className="min-w-0">
                    <CardTitle className="text-xl md:text-2xl font-bold truncate">{activeList.name}</CardTitle>
                    <CardDescription className="text-xs font-medium">
                      {activeList.items?.filter((i: any) => !i.checked).length} items left
                    </CardDescription>
                  </div>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" className="rounded-full"><MoreVertical className="h-5 w-5" /></Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="rounded-xl">
                      <DropdownMenuItem className="text-destructive font-bold" onClick={() => deleteList(activeList.id)}>
                        <Trash2 className="h-4 w-4 mr-2" /> Delete
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </CardHeader>
              <CardContent className="p-2 md:p-6 overflow-y-auto max-h-[60vh]">
                <div className="space-y-1">
                  {activeList.items?.map((item: any, index: number) => (
                    <div 
                      key={index}
                      onClick={() => toggleItem(activeList.id, index)}
                      className={`flex items-center gap-3 md:gap-4 p-3 md:p-4 rounded-xl cursor-pointer transition-all hover:bg-muted/30 ${
                        item.checked ? "opacity-40" : ""
                      }`}
                    >
                      <div className={`h-6 w-6 rounded-full border-2 flex items-center justify-center shrink-0 ${
                        item.checked ? "bg-emerald-500 border-emerald-500 text-white" : "border-muted-foreground/30"
                      }`}>
                        {item.checked && <CheckCircle2 className="h-4 w-4" />}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className={`font-bold text-sm md:text-base truncate ${item.checked ? "line-through" : ""}`}>
                          {item.name}
                        </div>
                        {item.category && <div className="text-[9px] font-bold text-primary uppercase">{item.category}</div>}
                      </div>
                      <div className="text-[10px] md:text-xs font-bold text-muted-foreground bg-muted/50 px-2 py-1 rounded-lg">
                        {item.quantity} {item.unit}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="text-center py-20 bg-muted/20 rounded-[2rem] border-2 border-dashed">
              <ListIcon className="h-12 w-12 text-muted-foreground/20 mx-auto mb-4" />
              <p className="text-sm text-muted-foreground">Select a list to view items</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
