
"use client"

import * as React from "react"
import { Mic, Search, Send, Sparkles, MicOff } from "lucide-react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { naturalLanguageQuickAdd } from "@/ai/flows/natural-language-quick-add"
import { useToast } from "@/hooks/use-toast"
import { useUser, useSupabase } from "@/supabase"

export function AIQuickAdd() {
  const [command, setCommand] = React.useState("")
  const [isLoading, setIsLoading] = React.useState(false)
  const [isListening, setIsListening] = React.useState(false)
  const { profile } = useUser()
  const supabase = useSupabase()
  const { toast } = useToast()

  // Voice Recognition Logic
  const startListening = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition
    if (!SpeechRecognition) {
      toast({ variant: "destructive", title: "Unsupported", description: "Voice recognition is not supported in this browser." })
      return
    }

    const recognition = new SpeechRecognition()
    recognition.lang = 'en-ZA' // South African English
    recognition.continuous = false
    recognition.interimResults = false

    recognition.onstart = () => setIsListening(true)
    recognition.onend = () => setIsListening(false)
    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript
      setCommand(transcript)
    }

    recognition.start()
  }

  const handleCommand = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!command.trim() || !profile?.familyId || !supabase) return

    setIsLoading(true)
    try {
      const { data: familyMembersData, error: memError } = await supabase.from("users").select("id, displayName").eq("familyId", profile.familyId)
      if (memError) throw memError

      const familyMembers = (familyMembersData || []).map((doc: any) => ({
        userId: doc.id,
        displayName: doc.displayName
      }))

      const result = await naturalLanguageQuickAdd({
        command: command,
        familyId: profile.familyId,
        userId: profile.id,
        familyMembers
      })

      if (result.type === "shoppingList") {
        const { data: existingLists, error: listError } = await supabase.from("shoppingLists")
          .select("*")
          .eq("familyId", profile.familyId).eq("name", result.listName)
        
        if (listError) throw listError
        
        if (existingLists && existingLists.length > 0) {
          const listDoc = existingLists[0]
          const currentItems = listDoc.items || []
          await supabase.from("shoppingLists").update({
            items: [...currentItems, { name: result.itemName, quantity: result.quantity || 1, unit: result.unit || "", category: result.category || "", checked: false }]
          }).eq("id", listDoc.id)
        } else {
          await supabase.from("shoppingLists").insert([{
            familyId: profile.familyId,
            name: result.listName,
            items: [{ name: result.itemName, quantity: result.quantity || 1, unit: result.unit || "", category: result.category || "", checked: false }],
            isAutoGenerated: false,
            createdAt: new Date().toISOString()
          }])
        }
      } else if (result.type === "todo") {
        await supabase.from("todos").insert([{
          familyId: profile.familyId,
          title: result.title,
          assignedTo: result.assignedTo,
          status: "pending",
          priority: result.priority || "medium",
          isShared: result.isShared,
          createdAt: new Date().toISOString()
        }])
      }

      setCommand("")
      toast({
        title: "Universe Command Executed",
        description: result.type === "todo" ? `Task "${result.title}" created.` : `Item "${result.itemName}" added.`,
      })
    } catch (error) {
      console.error(error)
      toast({
        variant: "destructive",
        title: "AI Failed",
        description: "I couldn't process that command. Try something like 'Add milk to groceries'.",
      })
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <form onSubmit={handleCommand} className="relative group w-full">
      <div className="absolute left-4 top-1/2 -translate-y-1/2 flex items-center gap-2 text-primary transition-colors group-focus-within:text-accent">
        <Sparkles className={`h-5 w-5 ${isLoading ? 'animate-spin' : 'animate-pulse'}`} />
      </div>
      <Input
        placeholder="Speak or type a command, ... (e.g. 'Buy bread')"
        className="h-16 pl-12 pr-28 rounded-2xl border-none shadow-xl shadow-primary/5 bg-white font-medium text-lg focus-visible:ring-accent/20"
        value={command}
        onChange={(e) => setCommand(e.target.value)}
        disabled={isLoading || !profile}
      />
      <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-2">
        <Button 
          type="button" 
          variant="ghost" 
          size="icon" 
          className={`h-12 w-12 rounded-xl transition-all ${isListening ? 'bg-rose-50 text-rose-500 animate-pulse' : 'hover:bg-muted'}`}
          onClick={startListening}
          disabled={isLoading}
        >
          {isListening ? <MicOff className="h-5 w-5" /> : <Mic className="h-5 w-5 text-muted-foreground" />}
        </Button>
        <Button 
          type="submit" 
          className="h-12 w-12 rounded-xl bg-accent hover:bg-accent/90 shadow-lg shadow-accent/20"
          disabled={isLoading || !command.trim()}
        >
          <Send className="h-5 w-5" />
        </Button>
      </div>
    </form>
  )
}
