
"use client"

import * as React from "react"
import { Mic, Search, Send, Sparkles, MicOff } from "lucide-react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { naturalLanguageQuickAdd } from "@/ai/flows/natural-language-quick-add"
import { useToast } from "@/hooks/use-toast"
import { useUser, useFirestore } from "@/firebase"
import { collection, query, where, getDocs, addDoc, serverTimestamp } from "firebase/firestore"

export function AIQuickAdd() {
  const [command, setCommand] = React.useState("")
  const [isLoading, setIsLoading] = React.useState(false)
  const [isListening, setIsListening] = React.useState(false)
  const { profile } = useUser()
  const db = useFirestore()
  const { toast } = useToast()

  // Voice Recognition Logic
  const startListening = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition
    if (!SpeechRecognition) {
      toast({ variant: "destructive", title: "Unsupported", description: "Voice recognition is not supported in this browser." })
      return
    }

    const recognition = new SpeechRecognition()
    recognition.lang = 'en-ZA' // South African English
    recognition.continuous = false
    recognition.interimResults = false

    recognition.onstart = () => setIsListening(true)
    recognition.onend = () => setIsListening(false)
    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript
      setCommand(transcript)
    }

    recognition.start()
  }

  const handleCommand = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!command.trim() || !profile?.familyId || !db) return

    setIsLoading(true)
    try {
      const membersSnap = await getDocs(query(collection(db, "users"), where("familyId", "==", profile.familyId)))
      const familyMembers = membersSnap.docs.map(doc => ({
        userId: doc.id,
        displayName: doc.data().displayName
      }))

      const result = await naturalLanguageQuickAdd({
        command: command,
        familyId: profile.familyId,
        userId: profile.id,
        familyMembers
      })

      if (result.type === "shoppingList") {
        const listQuery = query(
          collection(db, "shoppingLists"), 
          where("familyId", "==", profile.familyId),
          where("name", "==", result.listName)
        )
        const existingLists = await getDocs(listQuery)
        
        if (!existingLists.empty) {
          const listDoc = existingLists.docs[0]
          const currentItems = listDoc.data().items || []
          await addDoc(collection(db, "shoppingLists"), {
            ...listDoc.data(),
            items: [...currentItems, { name: result.itemName, quantity: result.quantity || 1, unit: result.unit || "", category: result.category || "", checked: false }]
          })
        } else {
          await addDoc(collection(db, "shoppingLists"), {
            familyId: profile.familyId,
            name: result.listName,
            items: [{ name: result.itemName, quantity: result.quantity || 1, unit: result.unit || "", category: result.category || "", checked: false }],
            isAutoGenerated: false,
            createdAt: serverTimestamp()
          })
        }
      } else if (result.type === "todo") {
        await addDoc(collection(db, "todos"), {
          familyId: profile.familyId,
          title: result.title,
          assignedTo: result.assignedTo,
          status: "pending",
          priority: result.priority || "medium",
          isShared: result.isShared,
          createdAt: serverTimestamp()
        })
      }

      setCommand("")
      toast({
        title: "Universe Command Executed",
        description: result.type === "todo" ? `Task "${result.title}" created.` : `Item "${result.itemName}" added.`,
      })
    } catch (error) {
      console.error(error)
      toast({
        variant: "destructive",
        title: "AI Failed",
        description: "I couldn't process that command. Try something like 'Add milk to groceries'.",
      })
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <form onSubmit={handleCommand} className="relative group w-full">
      <div className="absolute left-4 top-1/2 -translate-y-1/2 flex items-center gap-2 text-primary transition-colors group-focus-within:text-accent">
        <Sparkles className={`h-5 w-5 ${isLoading ? 'animate-spin' : 'animate-pulse'}`} />
      </div>
      <Input
        placeholder="Speak or type a command... (e.g. 'Buy bread')"
        className="h-16 pl-12 pr-28 rounded-2xl border-none shadow-xl shadow-primary/5 bg-white font-medium text-lg focus-visible:ring-accent/20"
        value={command}
        onChange={(e) => setCommand(e.target.value)}
        disabled={isLoading || !profile}
      />
      <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-2">
        <Button 
          type="button" 
          variant="ghost" 
          size="icon" 
          className={`h-12 w-12 rounded-xl transition-all ${isListening ? 'bg-rose-50 text-rose-500 animate-pulse' : 'hover:bg-muted'}`}
          onClick={startListening}
          disabled={isLoading}
        >
          {isListening ? <MicOff className="h-5 w-5" /> : <Mic className="h-5 w-5 text-muted-foreground" />}
        </Button>
        <Button 
          type="submit" 
          className="h-12 w-12 rounded-xl bg-accent hover:bg-accent/90 shadow-lg shadow-accent/20"
          disabled={isLoading || !command.trim()}
        >
          <Send className="h-5 w-5" />
        </Button>
      </div>
    </form>
  )
}
